default: &default
  adapter: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: my_database_development2

test:
  adapter: postgres
  database: my_database_test

production:
  adapter: postgres
  database: my_database_production
  username:
  password:
